name: Run action-dotnet-format

on:
  push:
    branches:
      - "feature/**"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  run-action-dotnet-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'
      - uses: tsubakimoto/action-dotnet-format@v1
        with:
          base-branch: ${{ github.ref_name }}
          project-path: 'src/SampleWebAppForActions/SampleWebAppForActions.csproj'
          verbosity: 'diag'
          github-token: ${{ secrets.GITHUB_TOKEN }}
